services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./webimagenes:/var/www/html/webimagenes
    environment:
      - TZ=Asia/Jerusalem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hidriverpro.rule=Host(`dev.hidriver.co.il`)"
      - "traefik.http.services.hidriverpro.loadbalancer.server.port=80"
      - "traefik.http.services.hidriverpro.loadbalancer.passHostHeader=true"
    restart: unless-stopped