services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # Remove explicit port mapping as Easypanel handles this through Traefik
    volumes:
      - ./src:/var/www/html
      - webimagenes_data:/var/www/html/webimagenes
    environment:
      - TZ=America/Mexico_City
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${service_name}.rule=Host(`${domain}`)"
      - "traefik.http.services.${service_name}.loadbalancer.server.port=80"
    restart: unless-stopped

volumes:
  webimagenes_data: