services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Changed to use port 8080 externally, mapping to internal port 80
    volumes:
      - ./src:/var/www/html
      - webimagenes_data:/var/www/html/webimagenes
    environment:
      - TZ=America/Mexico_City
      - PORT=80  # Fixed internal port to 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${service_name}.rule=Host(`${domain}`)"
      - "traefik.http.services.${service_name}.loadbalancer.server.port=80"  # Use internal port 80
    restart: unless-stopped

volumes:
  webimagenes_data: