version: '3.8'

services:
  web:
    image: yupiglobal/almalinux-php74:latest  # Cambiar por tu imagen en Docker Hub o registry
    ports:
      - "80:80"  # EasyPanel maneja el mapeo de puertos automáticamente
    volumes:
      - app_files:/var/www/html
      - webimagenes_data:/var/www/html/webimagenes
    environment:
      - TZ=America/Mexico_City
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped

volumes:
  app_files:
  webimagenes_data: