version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Changed from "80:80" to use port 8080 instead
    volumes:
      - ./src:/var/www/html
      - webimagenes_data:/var/www/html/webimagenes
    environment:
      - TZ=America/Mexico_City
    restart: unless-stopped

volumes:
  webimagenes_data: